repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.2"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes", "--output-format=full"]
        exclude: ^.*\.(ipynb)$
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.17.0"
    hooks:
      - id: mypy

  - repo: local
    hooks:
      - id: autogen-trainer-cfg
        name: Generate and verify verl/trainer/config/_generated_*.yaml
        entry: scripts/generate_trainer_config.sh
        language: script
        pass_filenames: false

      - id: check-docs-time-info
        name: Check docs Last updated info
        entry: python3 tests/special_sanity/check_docs_time_info.py
        language: python
        pass_filenames: false

      - id: check-docstrings
        name: Check doc string coverage
        entry: python3 tests/special_sanity/check_docstrings.py
        language: python
        pass_filenames: false

      - id: check-license
        name: Check license
        entry: python3 tests/special_sanity/check_license.py --directories .
        language: python
        pass_filenames: false

      - id: check-device-api-usage
        name: Check device API usage
        entry: python3 tests/special_sanity/check_device_api_usage.py --directory ./verl
        language: python
        pass_filenames: false

      - id: check-dataproto-usage
        name: Check DataProto usage
        entry: python3 tests/special_sanity/check_dataproto_usage.py -d ./verl/workers/engine
        language: python
        pass_filenames: false

      - id: validate-structure
        name: Validate test structure
        entry: python3 tests/special_sanity/validate_structure.py
        language: python
        pass_filenames: false

      - id: check-naming-conventions
        name: Check naming conventions
        entry: sh -c 'fail=0; if grep -rIn --exclude-dir=.git --exclude-dir=.github --exclude-dir=venv --exclude-dir=__pycache__ --exclude=.pre-commit-config.yaml "veRL" .; then echo "Please use verl instead of veRL"; fail=1; fi; if grep -rIn --exclude-dir=.git --exclude-dir=.github --exclude-dir=venv --exclude-dir=__pycache__ --exclude=ascend_sglang_best_practices.rst --exclude=.pre-commit-config.yaml -E "Sglang|sgLang|sglAng|sglaNg|sglanG" .; then echo "Please use SGLang or sglang"; fail=1; fi; exit $fail'
        language: system
        pass_filenames: false

      - id: check-example-naming
        name: Check example script naming convention
        entry: python3 tests/special_sanity/check_example_naming.py --root examples
        language: python
        pass_filenames: false

      - id: compileall
        name: Compile all python files
        entry: sh -c 'PYTHONWARNINGS=error python3 -m compileall -q . -x "(^|[\\/])(\.venv|venv|\.git|verl[\\/]experimental[\\/]vla)([\\/]|$)"'
        language: python
        pass_filenames: false
