# Pull base image
FROM swr.cn-south-1.myhuaweicloud.com/ascendhub/cann:8.5.0-a3-ubuntu22.04-py3.11

ARG SOC_VERSION="ascend910_9392"

ENV GIT_SSL_NO_VERIFY=true
RUN pip config --user set global.index https://mirrors.huaweicloud.com/repository/pypi && \
    pip config --user set global.index-url https://mirrors.huaweicloud.com/repository/pypi/simple && \
    pip config --user set global.trusted-host mirrors.huaweicloud.com
    
# Prepare required system dependencies
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends gcc g++ cmake libnuma-dev wget git curl jq vim build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    pip install --upgrade pip packaging setuptools==80.10.2 && \
    pip cache purge

# Prepare repositories with low update frequency
RUN ARCH=$(uname -m) && \
    # Set extra pip index for x86_64 platform
    echo "[LOG INFO] Detected architecture: $ARCH" && \
    if [ "$ARCH" = "x86_64" ]; then \
        pip config set global.extra-index-url "https://download.pytorch.org/whl/cpu/"; \
    fi && \
    # Clone libs
    git clone --depth 1 --branch v0.18.0 https://github.com/vllm-project/vllm.git && \
    git clone -b releases/v0.18.0 https://github.com/vllm-project/vllm-ascend.git && \
    git clone https://gitcode.com/Ascend/MindSpeed.git && \
    cd MindSpeed && git checkout 2.3.0_core_r0.12.1 && cd .. && \
    git clone --depth 1 --branch core_v0.12.1 https://github.com/NVIDIA/Megatron-LM.git

# Install repositories with low update frequency
RUN export PIP_EXTRA_INDEX_URL=https://triton-ascend.osinfra.cn/pypi/simple/ && \
    export PIP_TRUSTED_HOST=triton-ascend.osinfra.cn && \
    ARCH=$(uname -m) && \
    # Export and source env
    if [ "$ARCH" = "aarch64" ]; then \
        export LD_LIBRARY_PATH=/usr/local/Ascend/cann-8.5.0/aarch64-linux/devlib/linux/aarch64:$LD_LIBRARY_PATH; \
    elif [ "$ARCH" = "x86_64" ]; then \
        export LD_LIBRARY_PATH=/usr/local/Ascend/cann-8.5.0/x86_64-linux/devlib/linux/x86_64/:$LD_LIBRARY_PATH; \
    fi && \
    source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    source /usr/local/Ascend/nnal/atb/set_env.sh && \
    # Install transformers
    pip install transformers==4.57.6 && \
    # Install vllm
    cd vllm && pip install -r requirements/build.txt && \
    VLLM_TARGET_DEVICE=empty pip install -v -e. && cd .. && \
    if [ "$ARCH" = "x86_64" ]; then \
    pip install torch==2.9.0+cpu --index-url https://download.pytorch.org/whl/cpu/; \
    fi && \
    # Install vllm-ascend
    cd vllm-ascend && pip install -r requirements.txt && \
    export COMPILE_CUSTOM_KERNELS=1 && pip install --no-build-isolation --no-deps -v -e . && cd .. && \
    # Install MindSpeed & Megatron
    pip install -e MindSpeed && \
    pip install -e Megatron-LM && \
    # Remove existing triton installed by some third-party packages
    pip uninstall -y triton && \
    # Install mbridge
    pip install mbridge && \
    # Clear extra files
    rm -rf /tmp/* /var/tmp/* && \
    pip cache purge


# Prepare and install verl (update frequently)
RUN git clone --recursive https://github.com/verl-project/verl.git && \
    cd verl && pip install -r requirements-npu.txt && pip install -v -e . && cd .. && \
    # Clear extra files
    rm -rf /tmp/* /var/tmp/* && \
    pip cache purge

# Show install results
RUN pip list

# Setting Default Commands
CMD ["/bin/bash"]
