# Pull base image
FROM swr.cn-south-1.myhuaweicloud.com/ascendhub/cann:9.0.0-910b-ubuntu22.04-py3.11

ARG SOC_VERSION="ascend910b1"

# Prepare required system dependencies
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends gcc g++ cmake libnuma-dev wget git curl jq vim build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    pip install --upgrade pip packaging setuptools==80.10.2 && \
    pip cache purge

# Prepare repositories with low update frequency
RUN ARCH=$(uname -m) && \
    # Set extra pip index for x86_64 platform
    echo "[LOG INFO] Detected architecture: $ARCH" && \
    if [ "$ARCH" = "x86_64" ]; then \
        pip config set global.extra-index-url "https://download.pytorch.org/whl/cpu/"; \
    fi && \
    # Clone libs
    git clone --depth 1 --branch v0.18.0 https://github.com/vllm-project/vllm.git && \
    git clone -b releases/v0.18.0 https://github.com/vllm-project/vllm-ascend.git && \
    git clone https://gitcode.com/Ascend/MindSpeed.git && \
    cd MindSpeed && git checkout core_r0.16.0 && cd .. && \
    git clone --depth 1 --branch core_r0.16.0 https://github.com/NVIDIA/Megatron-LM.git && \
    git clone --depth 1 https://github.com/NVIDIA-NeMo/Megatron-Bridge.git && \
    cd Megatron-Bridge && git fetch --depth 1 origin de93536e9028ecf1e4dc28608dc80f336dcdfe59 && git checkout de93536e9028ecf1e4dc28608dc80f336dcdfe59 && cd .. && \
    git clone --depth 1 https://github.com/huggingface/transformers.git && \
    cd transformers && git fetch --depth 1 origin cc7ab9be508ce6ed3637bba9e50367b29b742dc6 && git checkout cc7ab9be508ce6ed3637bba9e50367b29b742dc6 && cd ..

# Install repositories with low update frequency
RUN export PIP_EXTRA_INDEX_URL=https://triton-ascend.osinfra.cn/pypi/simple/ && \
    export PIP_TRUSTED_HOST=triton-ascend.osinfra.cn && \
    ARCH=$(uname -m) && \
    # Export and source env
    if [ "$ARCH" = "aarch64" ]; then \
        export LD_LIBRARY_PATH=/usr/local/Ascend/cann-9.0.0/aarch64-linux/devlib/linux/aarch64:$LD_LIBRARY_PATH; \
    elif [ "$ARCH" = "x86_64" ]; then \
        export LD_LIBRARY_PATH=/usr/local/Ascend/cann-9.0.0/x86_64-linux/devlib/linux/x86_64/:$LD_LIBRARY_PATH; \
    fi && \
    source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    source /usr/local/Ascend/nnal/atb/set_env.sh && \
    # Install vllm
    cd vllm && pip install -r requirements/build.txt && \
    VLLM_TARGET_DEVICE=empty pip install -v -e. && cd .. && \
    if [ "$ARCH" = "x86_64" ]; then \
        pip install torch==2.9.0+cpu --index-url https://download.pytorch.org/whl/cpu/; \
        pip install torchvision==0.24.0+cpu --index-url https://download.pytorch.org/whl/cpu/; \
    fi && \
    # Install vllm-ascend
    cd vllm-ascend && pip install -r requirements.txt && \
    export COMPILE_CUSTOM_KERNELS=1 && pip install --no-build-isolation --no-deps -v -e . && cd .. && \
    # Install MindSpeed & Megatron
    pip install -e MindSpeed && \
    pip install -e Megatron-LM && \
    # Install transformers
    cd transformers && pip install -e . && cd .. && \
    # Install mbridge
    pip install mbridge && \
    # Install others
    pip install "nvidia-modelopt[torch]>=0.37.0" flash-linear-attention==0.5.0 qwen_vl_utils viztracer mathruler && \
    # Clear extra files
    rm -rf /tmp/* /var/tmp/* && \
    pip cache purge

# get mbridge path and cuda to npu for deepseek model
RUN MBRIDGE_PATH=$(pip show mbridge | grep Location | awk '{print $2}') && \
    TARGET_FILE="${MBRIDGE_PATH}/mbridge/models/ext/deepseek_v3/dequant_fp8_safetensor_io.py" && \
    sed -i '34s/cuda/npu/;51s/cuda/npu/' "$TARGET_FILE"


# Prepare and install verl  (verl is release/v0.8.0)
RUN git clone -b release/v0.8.0 https://github.com/verl-project/verl.git && cd verl && \
    git submodule update --init --recursive --remote && \
    pip install -r requirements-npu.txt && pip install -v -e . && cd .. && \
    # Clear extra files
    rm -rf /tmp/* /var/tmp/* && \
    pip cache purge

# set PYTHONPATH
ENV PYTHONPATH=/Megatron-Bridge/src:$PYTHONPATH

# Show install results
RUN pip list

# Setting Default Commands
CMD ["/bin/bash"]