# Pull base image
FROM swr.cn-south-1.myhuaweicloud.com/ascendhub/cann:8.5.0-a3-ubuntu22.04-py3.11

ARG PIP_INDEX_URL="https://mirrors.aliyun.com/pypi/simple"
ARG PTA_BASE_VERSION="torch_npu-2.8.0.post2-cp311-cp311-manylinux_2_28"
ARG PTA_URL="https://gitcode.com/Ascend/pytorch/releases/download/v7.3.0-pytorch2.8.0"

# Prepare required system dependencies
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends gcc g++ cmake libnuma-dev wget git curl jq vim build-essential net-tools iputils-ping unzip ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    pip config set global.index-url ${PIP_INDEX_URL} && \
    pip config set install.trusted-host mirrors.aliyun.com && \
    pip install --upgrade pip setuptools==80.10.2 packaging && \
    pip cache purge

# Prepare repositories with low update frequency
RUN ARCH=$(uname -m) && \
    echo "[LOG INFO] Detected architecture: $ARCH" && \
    # Set extra pip index for x86_64 platform
    if [ "$ARCH" = "x86_64" ]; then \
        pip config set global.extra-index-url "https://download.pytorch.org/whl/cpu/"; \
    fi && \
    # Clone libs
    git clone https://github.com/sgl-project/sglang.git && cd sglang && git checkout v0.5.10 && cd .. && \
    git clone https://gitcode.com/Ascend/MindSpeed.git && \
    cd MindSpeed && git checkout core_r0.16.0 && cd ..

# Install repositories with low update frequency
RUN cd sglang && \
    # Install sglang
    mv python/pyproject.toml python/pyproject.toml.backup && \
    mv python/pyproject_npu.toml python/pyproject.toml && \
    pip install torch==2.8.0 torchvision==0.23.0 && \
    # Install torch_npu
    ARCH=$(uname -m) && wget ${PTA_URL}/${PTA_BASE_VERSION}_${ARCH}.whl && pip install ${PTA_BASE_VERSION}_${ARCH}.whl && \
    echo "[LOG INFO] Torch_npu version is: ${PTA_BASE_VERSION}_${ARCH}.whl" && \
    pip install -e python[all_npu] && \
    pip install torch==2.8.0 torchvision==0.23.0 && \
    cd .. 

# Install sgl-kernel-npu
RUN ARCH=$(uname -m) && wget --no-check-certificate https://github.com/sgl-project/sgl-kernel-npu/releases/download/2026.02.01/sgl-kernel-npu-2026.02.01-torch2.8.0-py311-cann8.5.0-a3-${ARCH}.zip && \
    unzip sgl-kernel-npu*.zip && \
    pip install torch_memory_saver*.whl && \
    pip install sgl_kernel_npu*.whl && \
    pip install deep_ep*.whl

# Install MindSpeed & Megatron
RUN pip install -e MindSpeed && \
    pip install git+https://github.com/NVIDIA/Megatron-LM.git@core_r0.16.0 && \
    # Remove existing triton or triton-ascend installed by some third-party packages
    pip uninstall -y triton timm && \
    # Install mbridge
    pip install mbridge && \
    # Clear extra files
    rm -rf /tmp/* /var/tmp/* && \
    pip cache purge

# Prepare and install verl (update frequently)
RUN export PIP_EXTRA_INDEX_URL=https://triton-ascend.osinfra.cn/pypi/simple/ && \
    export PIP_TRUSTED_HOST=triton-ascend.osinfra.cn && \
    git clone --recursive https://github.com/volcengine/verl.git && \
    cd verl/recipe && git checkout main && cd .. && \
    pip install -r requirements-npu.txt && pip install -v -e . && cd .. && \
    pip install click==8.2.1 cachetools nvtx opencv-python-headless==4.10.0.84 && \
    # Clear extra files
    rm -rf /tmp/* /var/tmp/* && \
    pip cache purge

# Show install results
RUN pip list

# Setting Default Commands
CMD ["/bin/bash"]
